[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=23.3.0",
]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Perez Gobetti", email = "perez@gmail.com"},
]
dependencies = [
    "django>=4.1.7",
]
requires-python = ">=3.10"
license = {text = "MIT"}
